[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["dimaevan <dimaevan@gmail.com>"]
packages = [
    { include='gen_diff' },
]

[tool.poetry.scripts]
gendiff = "gen_diff.scripts.main:main"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
