name : myCI
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [ 3.8 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "Hello!"
      - run: echo "🐧This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make tests
